# Generated by Django 4.1.3 on 2022-12-07 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
    ]
